### ISSUE TITLE
Make autonomous routine that knows which side of the field it's on

### ISSUE THREAD

**Issue by nashirj** [smcrobotics/competition_bot_24_inch#4]
Steps:
1. Have a boolean that indicates which side and modify before each match as necessary
2. Place a limit switch on the robot that is depressed if on red side, and not if on blue, and use this to set the boolean that indicates side

**Comment by jeiook** [comment]
It looks like we currently do not have a limit switch.
Carlos had an idea for using a "jumper cable" that only has "on" or "off" state that we can plug into the 3-pin ports
It also looks like we don't have any other sensor (other than one limit switch that is no longer used now).

**Comment by AriYoung00** [comment]
Last I looked, we definitely had spare limit switches. We bought 4, and still had a few that we found with the old supplies, so it should still be feasible to use a limit switch rather than a jumper.

**Comment by AriYoung00** [comment]
In addition to that, we also have the distance sensor around somewhere. Are you guys sure you have the sensor box?

**Comment by jeiook** [comment]
Currently, it can detect which side it is on, but we still need the actual routines
